config/routes.rb
Rails.application.routes.draw do
  resources :activities do
    member do
      post 'add_worker'
      post 'remove_worker'
    end
  end
  resources :guest_groups, except: [:index]
  resources :camps do
    collection do
      post 'send_invite'
      post 'remove_account_from_camp'
      post 'get_report_data'
    end
    member do
      get 'camp_staff'
      get 'reporting'
    end
  end
  resources :accounts, except: [:show, :index]
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  patch "users/update"
  get "schedules/index"
  get "schedules/your_work_schedule"
  root "schedules#index"
end

app/models/camp.rb
class Camp < ApplicationRecord
  has_many :users, dependent: :delete_all
  has_many :accounts, through: :users
  has_many :guest_groups, dependent: :delete_all

  def set_variables(past)
    camp_accounts = self.accounts
    camp_pending_accounts = self.users.select{|u| u.account.nil?}
    if past != 'true'
      guest_groups = self.guest_groups.upcoming.order(:arrives)
    else
      guest_groups = self.guest_groups.past.order(:arrives)
    end

    return camp_accounts, camp_pending_accounts, guest_groups
  end

  def self.seed_messages
    Camp.all.each do |camp|
      camp.week_out_message = '<h4>[FirstName]</h4><p>Good news, you are on the schedule in a week! &nbsp;Take a look below to confirm the times that we have for you to work. Please give us a call if you have any questions or need to talk about you schedule.</p><p>[Blocks]</p>'
      camp.day_out_message = '<h4>[FirstName]</h4><p>Just a quick reminder about your work that is happening tomorrow. As always, please give us a call if there is any issues.</p><p>[Blocks]</p>'
      camp.save!
    end
  end
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  before_action :set_camp, only: [:show, :edit, :update, :destroy, :camp_staff, :reporting, :get_report_data]
  before_action :check_master_admin, only: [:create, :new, :destroy]
  before_action :check_camp_admin, only: [:edit, :update]
  before_action :set_variables, only: [:edit, :camp_staff, :index, :new]

  # GET /camps
  # GET /camps.json
  def index
    @camps = Camp.all
  end

  # GET /camps/1
  # GET /camps/1.json
  def show
  end

  # GET /camps/new
  def new
    @new_camp = Camp.new
  end

  # GET /camps/1/edit
  def edit
  end

  # POST /camps
  # POST /camps.json
  def create
    @camp = Camp.new(camp_params)
    @camp.week_out_message = '<h4>[FirstName]</h4><p>Good news, you are on the schedule in a week! &nbsp;Take a look below to confirm the times that we have for you to work. Please give us a call if you have any questions or need to talk about you schedule.</p><p>[Blocks]</p>'
    @camp.day_out_message = '<h4>[FirstName]</h4><p>Just a quick reminder about your work that is happening tomorrow. As always, please give us a call if there is any issues.</p><p>[Blocks]</p>'
    respond_to do |format|
      if @camp.save
        if User.invite!(:email => params[:user_email], camp_id: @camp.id, role: "camp_admin")
          format.html { redirect_to @camp, notice: 'Camp and user was successfully created.' }
          format.json { render :show, status: :created, location: @camp }
        else
          format.html { render :new }
          format.json { render json: {"User Error" => "Not able to send email"}, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /camps/1
  # PATCH/PUT /camps/1.json
  def update
    respond_to do |format|
      if @camp.update(camp_params)
        format.html { redirect_to root_path, notice: 'Camp was successfully updated.' }
        format.json { render :show, status: :ok, location: @camp }
      else
        format.html { render :edit }
        format.json { render json: @camp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /camps/1
  # DELETE /camps/1.json
  def destroy
    @camp.destroy
    respond_to do |format|
      format.html { redirect_to camps_url, notice: 'Camp was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  def send_invite
    respond_to do |format|
      if User.invite!(:email => params[:invite_email], camp_id: current_user.camp_id)
        format.js { flash.now[:notice] = "Invite Email Sent" }
      else
        format.js { flash.now[:alert] = "There has been an error, please try again" }
      end
    end
  end

  def remove_account_from_camp
    if params["account"].present?
      @account = Account.find(params["account"])
      user = @account.user
    else
      user = User.find(params["user"])
    end

    user.activities.clear
    respond_to do |format|
      if user.delete
        format.js { flash.now[:notice] = "Removed #{defined?(@account) ? @account.name_with_initial : user.email} from camp's staff list" }
      else
        format.js { flash.now[:alert] = "There has been an error, please try again" }
      end
    end
  end

  def camp_staff
  end

  def reporting
    @all_staff_members = @camp.accounts
    @all_guest_groups = @camp.guest_groups
  end

  def get_report_data
    activities = Activity.joins(guest_group: :camp).where("camps.id = ? AND day >= ? and day <= ?", @camp.id, params[:report_start], params[:report_ends])
    users = activities.map(&:users).flatten.uniq
    @activity_users = {}
    users.each do |user|
      @activity_users[user] = activities.select{|a| a.users.include? user}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camp
      @camp = Camp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def camp_params
      params.require(:camp).permit(:name, :website, :phone_number, :week_out_message, :day_out_message)
    end

    def check_master_admin
      unless current_user.master_admin?
        redirect_to root_path, alert: 'Not allowed to perform this function'
      end
    end

    def check_camp_admin
      unless (current_user.master_admin? || current_user.camp_admin?) && current_user.camp_id == @camp.id
        redirect_to root_path, alert: 'Not allowed to perform this function'
      end
    end
end

app/helpers/camps_helper.rb
module CampsHelper
end

app/views/camps/_display_pending_staff.html.erb
<div class="col">
  <div class="card">
    <div class="card-header">
      Pending Staff Members Invites
    </div>
    <table class='table'>
      <%pending.each do |staff|%>
        <tr>
          <td><%=staff.email%></td>
          <td>
            <%= link_to remove_account_from_camp_camps_path(user: staff), method: :post, class: 'btn btn-xs btn-danger text-white', :remote => true do %>
              Cancel Invite
            <%end%>
          </td>
        </tr>
      <%end%>
    </table>
  </div>
</div>

app/views/camps/_display_report.html.erb
<%if activity_users.blank?%>
  <p>There are no worked blocks to display during the times selected</p>
<%else%>
  <div class='row'>
    <div class="col">
      <%report_total_time = 0%>
      <%activity_users.each do |user, activities|%>
        <div class='card bg-light mb-3'>
          <div class='card-header py-1 px-2'>
            <div class='row'>
              <div class='col'><%=user.account.full_name%></div>
              <div class='col'><%=activities.count%> Activities</div>
            </div>
          </div>
          <div class='card-body py-1'>
            <%user_total_time = 0%>
            <%activities.each do |activity|%>
              <%
                start_time = Time.new(activity.day.year, activity.day.month, activity.day.day, activity.start.hour, activity.start.min)
                end_time = Time.new(activity.end_date.year, activity.end_date.month, activity.end_date.day, activity.end.hour, activity.end.min)
              %>
              <%user_total_time += (end_time - start_time).to_i.abs%>
              <div class='row'>
                <div class='col'><%=activity.name%></div>
                <div class='col'><%= link_to activity.guest_group.name, guest_group_path(activity.guest_group)%></div>
                <div class='col'><%=activity.day_and_time_span%></div>
                <div class='col'><%=Activity.time_diff((end_time - start_time).to_i.abs)%> hours</div>
              </div>
            <%end%>
          </div>
          <div class='card-footer py-1'>
            <div class='row'>
              <div class='col text-right'>
                Total Hours Worked: <%=Activity.time_diff(user_total_time)%>
              </div>
            </div>
          </div>
        </div>
        <%report_total_time += user_total_time%>
      <%end%>
    </div>
  </div>

  <div class='row'>
    <div class='col text-right'>
      Total Hours Worked for the Report: <%=Activity.time_diff(report_total_time)%>
    </div>
  </div>
<%end%>

app/views/camps/_form.html.erb
<%= render "layouts/error_display", errors: camp.errors%>

<%= form_with(model: camp, local: true, id: 'camp-form') do |form| %>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col">
              <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control" %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <%= form.label :website %>
                <%= form.text_field :website, class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-6 ">
              <div class="form-group">
                <%= form.label :phone_number %><br />
                <%= form.text_field :phone_number, class: "form-control" %>
              </div>
            </div>
            <%if params["action"] == "new"%>
              <div class="col">
                <div class="form-group">
                  <%= label_tag "User Email Address" %><br />
                  <%= text_field_tag "user_email", nil, class: "form-control" %>
                </div>
              </div>
            <%end%>
          </div>

          <%if params["action"] != "new"%>
            <p>
              You can use the two areas below to customize the week out and day out emails that go to staff working blocks. If you would like to 
              customize the email by inserting the staff's name, plese use "[FirstName]" and "[LastName]" to designate those areas. If you would
              like to specify where the information about their blocks is displayed, use "[Blocks]" to designate it. If you dont include the block
              tag then it will automatically be displayed at the bottom of the email.
            </p>
          
            <div class="row">
              <div class="col">
                <%= label_tag "Week Out Message" %>
                <textarea name="camp[week_out_message]" id="camp_week_out_message">
                  <% if camp.week_out_message.blank?%>
                    <h3>[FirstName]</h3><br />
                    <p>Good news, you are on the schedule in a week! Take a look below to confirm the times that we have for you to work. Please give us a call if you have any questions or need to talk about you schedule.</p><br/>
                    [Blocks]
                  <%else%>
                    <%=camp.week_out_message%>
                  <%end%>
                </textarea>
              </div>
            </div>

            <div class="row mt-3">
              <div class="col">
                <%= label_tag "Day Before Message" %>
                <textarea name="camp[day_out_message]" id="camp_day_out_message">
                  <% if camp.day_out_message.blank?%>
                    <h3>[FirstName]</h3><br />
                    <p>Just a quick reminder about your work that is happening tomorrow. As always, please give us a call if there is any issues.</p><br />
                    [Blocks]
                  <%else%>
                    <%=camp.day_out_message%>
                  <%end%>
                </textarea>
              </div>
            </div>
          <%end%>

        </div>
        <div class="card-footer text-right">
          <%= form.submit "Save", class: "btn btn-success" %>
          <%= link_to 'Cancel', root_path, class: "btn btn-danger text-white" %>
        </div>
      </div>
    </div>
  </div>
<%end%>
<%content_for :bottom_script do%>
  <script>
    $(document).ready(function(){
      $("#camp_phone_number").mask('(000) 000-0000');
    });

    ClassicEditor
      .create( document.querySelector( '#camp_day_out_message' ), {
        toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList' ],
      } )
      .catch( error => {
          console.error( error );
      } );
    
    ClassicEditor
      .create( document.querySelector( '#camp_week_out_message' ), {
        toolbar: [ 'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList' ],
      } )
      .catch( error => {
          console.error( error );
      } );
  </script>
<%end%>

app/views/camps/camp_staff.html.erb
<div class="row">
  <%=form_tag send_invite_camps_path, remote: true, class: "col" do%>
    <div class='form-group row align-items-center'>
      <div class='col-auto'>
        Add New Staff Member
      </div>
      <%=text_field_tag "invite_email", nil, placeholder: "Enter email", class: "form-control col-4 mr-5"%>
      <%=submit_tag "Send Invite", class: "btn btn-primary btn-sm btn-block col-2"%>
    </div>
  <%end%>
</div>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        Staff Members
      </div>
      <table class='table'>
        <%@camp_accounts.sort_by(&:last_name).each do |staff|%>
          <tr id="<%=staff.id.to_s%>_staff_listing">
            <td><%=staff.full_name%></td>
            <td><%=mail_to staff.user.email, "<i class='fas fa-envelope'></i> #{staff.user.email}".html_safe, class: 'btn btn-link btn-xs'%></td>
            <td><%=link_to "<i class='fas fa-phone-alt'></i> #{staff.phone_number}".html_safe, "tel:#{staff.phone_number}", class: 'btn btn-link btn-xs' unless staff.phone_number.blank?%></td>
            <td class="text-right">
              <%=link_to("Make #{staff.user.role == 'user' ? 'Admin' : 'Staff'}", users_update_path(id: staff.user), method: :patch, class: "btn btn-xs #{staff.user.role == 'user' ? 'btn-primary' : 'btn-info'} mb-1 change-status", remote: true) unless current_user.camp_admin? || current_user.account == staff%>
              <%= link_to remove_account_from_camp_camps_path(account: staff), method: :post, class: 'btn btn-xs btn-danger text-white mb-1', :remote => true do %>
                Delete User
              <% end %>
            </td>
          </tr>
        <%end%>
      </table>
    </div>
  </div>
</div>

<div class="row mt-3" id='pending-staff'>
  <%=render 'display_pending_staff', pending: @camp_pending_accounts unless @camp_pending_accounts.blank?%>
</div>

app/views/camps/edit.html.erb
<h1>Update <%=@camp.name%></h1>

<%= render 'form', camp: @camp %>

<%#= link_to 'Show', @camp %>
<%#= link_to ' | Back', camps_path %>

app/views/camps/get_report_data.js.erb
$("#report_display").html("<%= j render 'display_report', activity_users: @activity_users %>")

app/views/camps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Camps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @camps.each do |camp| %>
      <tr>
        <td><%= camp.name %></td>
        <td><%= camp.website %></td>
        <td><%= camp.phone_number %></td>
        <td><%= link_to 'Show', root_path(camp: camp.id) %></td>
        <td><%= link_to 'Edit', edit_camp_path(camp) %></td>
        <td><%= link_to 'Destroy', camp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camp', new_camp_path %>

app/views/camps/new.html.erb
<h1>New Camp</h1>

<%= render 'form', camp: @new_camp %>

<%#= link_to 'Back', camps_path %>

app/views/camps/remove_account_from_camp.js.erb
<%if flash[:notice]%>
  $("#info").html("<%= flash[:notice] %>").show(function() {
    setTimeout(function() {
      $("#info").fadeOut('slow');
    }, 4000)
  });
  $('#<%=params["account"]%>_staff_listing').remove();
<%elsif flash[:alert]%>
  $("#alert").html("<%= flash[:alert] %>").show(function() {
    setTimeout(function() {
      $("#alert").fadeOut('slow');
    }, 4000)
  })
<%end%>
$("#invite_email").val("")
<%accounts = current_user.camp.accounts%>
<%pending = current_user.camp.users.select{|u| u.account.nil?}%>
$("#pending-staff").html("")
<%unless pending.empty?%>
  $("#pending-staff").html("<%= escape_javascript render 'display_pending_staff', pending: pending %>")
<%end%>

app/views/camps/reporting.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <%= form_with url: get_report_data_camps_path, remote: true do |form| %>
          <div class="row d-print-none">
            <div class="col">
              Select date for report to start: <%= form.date_field :report_start, value: Date.today() - 7.days, class: "form-control" %>
            </div>
            <div class="col">
              Select date for report to end: <%= form.date_field :report_ends, value: Date.today(), class: "form-control" %>
            </div>
            <div class="col-auto">
              <%= form.submit 'Run Report', class:'btn btn-success mt-4'%>
            </div>
            <%=hidden_field_tag 'id', @camp.id%>
          </div>
        <% end %>
        <div class='row mt-5 d-none d-print-block'>
          <div class='col'>
            <h2>Hours Worked Report | <span id='report-start'></span> - <span id='report-end'></span></h2>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col" id="report_display">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  updatePrintInfo()

  $('#report_start, #report_ends').change(function() {
    updatePrintInfo()
  });

  function updatePrintInfo() {
    $("#report-start").html($('#report_start').val().split("-").reverse().join("/"))
    $("#report-end").html($('#report_ends').val().split("-").reverse().join("/"))
  }
</script>

app/views/camps/send_invite.js.erb
<%if flash[:notice]%>
  $("#info").html("<%= flash[:notice] %>").show(function() {
    setTimeout(function() {
      $("#info").fadeOut('slow');
    }, 4000)
  });
  $('#invite_email').val("");
  $('#invite-field').hide();
<%elsif flash[:alert]%>
  $("#alert").html("<%= flash[:alert] %>").show(function() {
    setTimeout(function() {
      $("#alert").fadeOut('slow');
    }, 4000)
  })
  $('#invite_email').addClass("border-danger");
<%end%>
<%accounts = current_user.camp.accounts%>
<%pending = current_user.camp.users.select{|u| u.account.nil?}%>
<%unless pending.empty?%>
  $("#pending-staff").html("<%= escape_javascript render 'display_pending_staff', pending: pending %>")
<%end%>

app/views/camps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @camp.name %>
</p>

<p>
  <strong>Website:</strong>
  <%= @camp.website %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @camp.phone_number %>
</p>

<%= link_to 'Edit', edit_camp_path(@camp) %> |
<%= link_to 'Back', camps_path %>