config/routes.rb
Rails.application.routes.draw do
  resources :activities do
    member do
      post 'add_worker'
      post 'remove_worker'
    end
  end
  resources :guest_groups, except: [:index]
  resources :camps do
    collection do
      post 'send_invite'
      post 'remove_account_from_camp'
      post 'get_report_data'
    end
    member do
      get 'camp_staff'
      get 'reporting'
    end
  end
  resources :accounts, except: [:show, :index]
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  patch "users/update"
  get "schedules/index"
  get "schedules/your_work_schedule"
  root "schedules#index"
end

app/models/guest_group.rb
class GuestGroup < ApplicationRecord
  #name, description, arrives, leaves
  validates :name, :arrives, :leaves, presence: true
  #validate :dates_correct?
  
  #default_scope {where("leaves >= ?", Date.today())}

  belongs_to :camp
  has_many :activities, dependent: :delete_all
  accepts_nested_attributes_for :activities, allow_destroy: true

  scope :upcoming, -> { where("leaves >= ?", Date.today())}
  scope :past, -> { where("leaves < ?", Date.today())}

  def dates_correct?
    if arrives < Date.today()
      errors.add(:arrives, 'Arriving date cannot be in the past')
    end
    if leaves < Date.today()
      errors.add(:leaves, 'Leaving date cannot be in the past')
    end
    if leaves < arrives
      errors.add(:leaves, 'Cannot select a leaving date that is before the arriving date')
    end
  end
end

app/controllers/guest_groups_controller.rb
class GuestGroupsController < ApplicationController
  before_action :set_guest_group, only: [:show, :edit, :update, :destroy]
  before_action :set_variables, only: [:new, :edit, :show, :update]

  # GET /guest_groups
  # GET /guest_groups.json
  #def index
    #@guest_groups = GuestGroup.all
  #end

  # GET /guest_groups/1
  # GET /guest_groups/1.json
  def show
  end

  # GET /guest_groups/new
  def new
    if current_user.camp_admin? || current_user.master_admin?
      @guest_group = GuestGroup.new
      @activities = [@guest_group.activities.build]
    else
      redirect_to root_path, alert: 'Not authorized to create a group'
    end
  end

  # GET /guest_groups/1/edit
  def edit
    @activities = Activity.order_by_start(@guest_group.activities)
  end

  # POST /guest_groups
  # POST /guest_groups.json
  def create
    @guest_group = GuestGroup.new(guest_group_params)
    respond_to do |format|
      if @guest_group.save
        format.html { redirect_to root_path, notice: 'Guest group was successfully created.' }
        format.json { render :show, status: :created, location: @guest_group }
      else
        format.html { render :new }
        format.json { render json: @guest_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guest_groups/1
  # PATCH/PUT /guest_groups/1.json
  def update
    #send email update if any activities are Removed
    activities_to_remove = params["guest_group"]["activities_attributes"].select{|a, data| data["_destroy"] == "1"}
    alet_users_of_deleted_activites(activities_to_remove) unless activities_to_remove.empty?

    #remove any work assignments
    activities_to_remove.each do |_i, act_param|
      Activity.find(act_param["id"].to_i).users.clear
    end

    respond_to do |format|
      if @guest_group.update(guest_group_params)
        format.html { redirect_to root_path, notice: 'Guest group was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest_group }
      else
        format.html { render :edit }
        format.json { render json: @guest_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guest_groups/1
  # DELETE /guest_groups/1.json
  def destroy
    #send email update if any activities are Removed
    alet_users_of_deleted_activites(@guest_group.activities)

    #remove any work assignments
    @guest_group.activities.each do |activity|
      activity.users.clear
    end

    if current_user.camp_admin? || current_user.master_admin?
      @guest_group.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Guest group was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, alert: 'Not authorized to delete a group'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest_group
      @guest_group = GuestGroup.find(params[:id])
    end

    #send emails if activity is deleted
    def alet_users_of_deleted_activites(deleted_activities)
      @guest_group.camp.accounts.each do |account|
        user = account.user
        ids = []
        if params["_method"] == "delete"
          ids = deleted_activities.map(&:id)
        else
          deleted_activities.each{|_i, data| ids << data["id"].to_i}
        end
        working_deleted_activities = user.activities.where(id: ids)
        unless working_deleted_activities.empty?
          WorkNotifierMailer.activities_deleted(account, working_deleted_activities, @guest_group.name).deliver!
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_group_params
      params.require(:guest_group).permit(:name, :description, :arrives, :leaves, :camp_id, activities_attributes: [:id, :name, :day, :start, :end_date, :end, :staff_needed, :activity_type, :_destroy])
    end
end

app/helpers/guest_groups_helper.rb
module GuestGroupsHelper
end

app/views/guest_groups/_activity_fields.html.erb
<div class="card nested-fields mb-3">
  <div class="card-body">
    <div class="row">
      <%= f.hidden_field :id %>
      <div class="col-lg-8 form-group field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-lg-4 form-group field">
        <%= f.label :staff_needed, "Number Staff Needed" %>
        <%= f.number_field :staff_needed, class: "form-control" %>
      </div>
    </div>
    <div class='row mb-3'>
      <div class='col-lg-auto'>
        <%Activity.activity_types.keys.each do |activity_type|%>
          <div class="custom-control custom-radio  custom-control-inline">
            <%=f.radio_button :activity_type, activity_type, class: 'custom-control-input'%>
            <%= f.label "#{:activity_type}_#{activity_type.parameterize.underscore}", activity_type.humanize.titleize, class: 'custom-control-label' %> <!--need to get this right!-->
          </div>
        <%end%>
      </div>
    </div>
    <div class='row'>
      <div class="col-lg-auto form-group field">
        <%= f.label :day, "Start Day" %>
        <div class="d-flex form-group field">
          <%min_date = (f.object.day.nil? ? Date.today : f.object.day)%>
          <%= f.date_field :day, default: Date.today(), class: "form-control" %>
        </div>
      </div>
      <div class="col-lg-3 start_time" style='<%="display: none;".html_safe if f.object.activity_type == 'all_day'%>'>
        <%= f.label :start %><br />
        <div class="d-flex form-group field">
          <%= f.time_select :start, {minute_step: 15, ampm: true, time_separator: ""}, {class: "form-control"} %>
        </div>
      </div>
      <div class="col-lg-auto form-group field end_date" style='<%="display: none;".html_safe if ['hourly', 'all_day'].include?(f.object.activity_type)%>'>
        <%= f.label :end_date, "End Day" %>
        <div class="d-flex form-group field">
          <%min_date = (f.object.day.nil? ? Date.today : f.object.day)%>
          <%= f.date_field :end_date, default: Date.today(), class: "form-control" %>
        </div>
      </div>
      <div class="col-lg-3 end_time" style='<%="display: none;".html_safe if f.object.activity_type == 'all_day'%>'>
        <%= f.label :end %>
        <div class="d-flex form-group field">
          <%= f.time_select :end, {minute_step: 15, ampm: true, time_separator: ""}, {class: "form-control"} %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12 text-right">
        <%= link_to_remove_association "Remove Activity", f, class: "btn btn-danger text-white"%>
      </div>
    </div>
  </div>
</div>

<script>
  jQuery("input[type='radio']").change(function() {
    if(jQuery(this).val() == 'multi_day') {
      jQuery(this).closest('.row').next().find('.end_date, .start_time, .end_time').show()
    }else if(jQuery(this).val() == 'all_day'){
      jQuery(this).closest('.row').next().find('.end_date, .start_time, .end_time').hide()
    }else if(jQuery(this).val() == 'hourly'){
      jQuery(this).closest('.row').next().find('.start_time, .end_time').show()
      jQuery(this).closest('.row').next().find('.end_date').hide()
    }
  })
</script>

app/views/guest_groups/_display_group.html.erb
<div class="card mb-3 gg_card">
  <div class="card-body">
    <div class="row justify-content-between">
      <div class="col-auto d-flex">
        <h4 class="card-title mr-3">
          <%if current_user.previously_seen_at.nil?%>
            <span class="text-primary">New</span> -
          <%elsif gg.updated_at > current_user.previously_seen_at%>
            <span class="text-primary">New</span> -
          <%end%>
          <span class="gg_name"><%=gg.name%></span>
        </h4>
      </div>
      <div class="col-auto">
        <h5 class="card-title"><%=gg.arrives.strftime("%a, %b %e")%> - <%=gg.leaves.strftime("%a, %b %e")%></h5>
      </div>
    </div>
    <div class="row justify-content-between">
      <div class="col">
        <span class="text-muted"><%=gg.description%></span>
      </div>
    </div>
    <div id="accordion-gg<%=gg.id%>" class="mt-3">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-gg<%=gg.id%>" aria-expanded="true" aria-controls="collapse-gg<%=gg.id%>">
              <%=gg.activities.count%> <%="Activity".pluralize(gg.activities.count)%> (Click to view)
            </button>
          </h5>
        </div>

        <div id="collapse-gg<%=gg.id%>" class="collapse" aria-labelledby="headingOne" data-parent="#accordion-gg<%=gg.id%>">
          <div class="card-body">
            <%Activity.order_by_start(gg.activities).each do |activity|%>
              <%=render "activities/display_activity", activity: activity%>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%if current_user.camp_admin? || current_user.master_admin?%>
    <div class="card-footer text-right">
      <div class='row justify-content-end'>
        <div class='col-6 col-md-auto'>
          <%= link_to "Edit Group", edit_guest_group_path(gg), class: "btn btn-sm btn-block btn-primary text-white" %>
        </div>
        <div class='col-6 col-md-auto'>
          <%= link_to "Delete Group", gg, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-block btn-danger text-white" %>
        </div>
      </div> 
    </div>
  <%end%>
</div>

app/views/guest_groups/_form.html.erb
<%= render "layouts/error_display", errors: guest_group.errors%>

<%= form_with(model: guest_group, local: true) do |form| %>
  <div class="row py-3 d-md-none" style='position: sticky; top: 78px; z-index: 10; background: rgba(18, 28, 71, 1); margin: -30px; margin-right: -30px; margin-top: -15px;'>
    <div class="col-6">
      <%= form.submit "Save All", class: "btn btn-block btn-success" %>
    </div>
    <div class="col-6">
      <%= link_to 'Cancel', root_path, class: "btn btn-danger btn-block text-white" %>
    </div>
  </div>

  <div class="d-md-none mt-5"></div>

  <div class='row align-items-center'>
    <div class='col-auto'>
      <h1><%=params[:action].titleize%> Guest Group</h1>
    </div>
    <div class='col-auto'>
      <%= link_to 'Back to All Groups', root_path, class: 'btn btn-primary text-white'%>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-3">
      <div class="row">
        <div class="col-12">
          <h5>Group Info</h5>
        </div>
      </div>
      <div class="card">
        <div class="card-body">
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :description %>
            <%= form.text_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :arrives %><br />
            <%= form.date_field :arrives, default: Date.today(), class: "form-control" %>
            <%#= form.date_field :arrives, min: form.object.arrives.blank? ? Date.today : nil, default: Date.today(), class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :leaves %>
            <%= form.date_field :leaves, default: Date.today()+1, class: "form-control" %>
            <%#= form.date_field :leaves, min: form.object.leaves.blank? ? Date.today : nil, default: Date.today()+1, class: "form-control" %>
          </div>
          <%=form.hidden_field :camp_id, value: current_user.camp_id%>
        </div>
      </div>
    </div>
    <div class="col-lg-9">
      <div class="row">
        <div class="col-12">
          <h5>Programs</h5>
        </div>
      </div>
      <div id="activities">
        <%=form.fields_for :activities, @activities do |activity|%>
          <%=render "activity_fields", f: activity%>
        <%end%>
        <div class='links'>
          <%=link_to_add_association 'Add Activity', form, :activities, class: "btn btn-primary text-white mt-2"%>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-right d-none d-md-block">
      <%= form.submit "Save Group and Activities", class: "btn btn-success" %>
      <%= link_to 'Cancel', root_path, class: "btn btn-danger text-white" %>
    </div>
  </div>
<% end %>
<%content_for :bottom_script do%>
  <script>
    $(document).ready(function(){
      $( "#guest_group_leaves_3i, #guest_group_leaves_1i" ).wrapAll( "<div  class='d-flex mb-3' />");
      $( "#guest_group_leaves_4i, #guest_group_leaves_5i" ).wrapAll( "<div  class='d-flex' />");
      $( "#guest_group_arrives_3i, #guest_group_arrives_1i" ).wrapAll( "<div  class='d-flex mb-3' />");
      $( "#guest_group_arrives_4i, #guest_group_arrives_5i" ).wrapAll( "<div  class='d-flex' />");
    });
  </script>
<%end%>

app/views/guest_groups/edit.html.erb
<!--<div class="row justify-content-between align-items-center">
  <div class='col'>
    <h1>Editing Guest Group</h1>
  </div>
  <div class='col-auto'>
    <%= link_to 'Back to All Groups', root_path, class: 'btn btn-primary text-white'%>
  </div>
</div>-->

<%= render 'form', guest_group: @guest_group %>

<%#= link_to 'Show | ', @guest_group %>
<%#= link_to 'Back', guest_groups_path %>

app/views/guest_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Guest Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Arrives</th>
      <th>Leaves</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guest_groups.each do |guest_group| %>
      <tr>
        <td><%= guest_group.name %></td>
        <td><%= guest_group.description %></td>
        <td><%= guest_group.arrives %></td>
        <td><%= guest_group.leaves %></td>
        <td><%= link_to 'Show', guest_group %></td>
        <td><%= link_to 'Edit', edit_guest_group_path(guest_group) %></td>
        <td><%= link_to 'Destroy', guest_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guest Group', new_guest_group_path %>

app/views/guest_groups/new.html.erb
<!--<h1>New Guest Group</h1>-->

<%= render 'form', guest_group: @guest_group %>

<%#= link_to 'Back', guest_groups_path, class: "btn btn-danger btn-sm float-right" %>

app/views/guest_groups/show.html.erb
<div class="card mb-3 gg_card">
  <div class="card-body">
    <div class="row justify-content-between">
      <div class="col-auto d-flex">
        <h4 class="card-title mr-3">
          <%if current_user.previously_seen_at.nil?%>
            <span class="text-primary">New</span> -
          <%elsif @guest_group.updated_at > current_user.previously_seen_at%>
            <span class="text-primary">New</span> -
          <%end%>
          <span class="gg_name"><%=@guest_group.name%></span>
        </h4>
      </div>
      <div class="col-auto">
        <h5 class="card-title"><%=@guest_group.arrives.strftime("%a, %b %e")%> - <%=@guest_group.leaves.strftime("%a, %b %e")%></h5>
      </div>
    </div>
    <div class="row justify-content-between">
      <div class="col">
        <span class="text-muted"><%=@guest_group.description%></span>
      </div>
    </div>
    <div id="accordion-gg<%=@guest_group.id%>" class="mt-3">
      <div class="card">
        <div class="card-header" id="headingOne">
          <h5 class="mb-0">
            <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-gg<%=@guest_group.id%>" aria-expanded="true" aria-controls="collapse-gg<%=@guest_group.id%>">
              <%=@guest_group.activities.count%> <%="Activity".pluralize(@guest_group.activities.count)%>
            </button>
          </h5>
        </div>

        <div id="collapse-gg<%=@guest_group.id%>" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion-gg<%=@guest_group.id%>">
          <div class="card-body">
            <%@guest_group.activities.each do |activity|%>
              <%=render "activities/display_activity", activity: activity%>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>