config/routes.rb
Rails.application.routes.draw do
  resources :activities do
    member do
      post 'add_worker'
      post 'remove_worker'
    end
  end
  resources :guest_groups, except: [:index]
  resources :camps do
    collection do
      post 'send_invite'
      post 'remove_account_from_camp'
      post 'get_report_data'
    end
    member do
      get 'camp_staff'
      get 'reporting'
    end
  end
  resources :accounts, except: [:show, :index]
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  patch "users/update"
  get "schedules/index"
  get "schedules/your_work_schedule"
  root "schedules#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
  #name, day, start, end, staff_needed
  validates :name, :day, :start, :end, :staff_needed, presence: true
  validate :day_in_guest_group?
  validate :start_before_end?

  enum activity_type: [:hourly, :all_day, :multi_day]

  belongs_to :guest_group, optional: true
  has_and_belongs_to_many :users

  before_validation :modify_dates_bsaed_of_activity_type
  before_destroy { users.clear }

  #scope :order_by_start, -> { order(day: :asc, start: :desc) }
  scope :upcoming, -> { where("day >= ?", Date.today())}
  scope :past, -> { where("day < ?", Date.today())}

  def day_and_time_span
    output = ''
    output += "#{self.day.strftime("%a, %b %e")} "
    if self.activity_type != 'all_day'
      output += "#{self.start.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M")} - "
      if self.day != self.try(:end_date) && !self.end_date.nil?
        output += "#{self.end_date.strftime("%a, %b, %e")} "
      end
      output += "#{self.end.in_time_zone('Eastern Time (US & Canada)').strftime("%l:%M %P")}"
    else
      output += "- All Day"
    end
    return output
  end

  def self.order_by_start(activities)
    activities.sort_by{|a| [a.day, a.start.to_s(:time)]}
  end

  def day_in_guest_group?
    group = self.guest_group
    if day < group.arrives.to_date || day > group.leaves.to_date #(group.arrives..group.leaves).include?(day)
      errors.add(:day, "needs to be inbetween group's arriving and leaving date")
    end

    if self.activity_type == 'multi_day' && (self.end_date < group.arrives.to_date || self.end_date > group.leaves.to_date)
      errors.add(:end_date, "needs to be inbetween group's arriving and leaving date")
    end
  end

  def start_before_end?
    #gotta test depending on what the type is
    case self.activity_type
      when 'hourly'
        if self.end.strftime('%T') < self.start.strftime('%T')
          errors.add(:end, "time must be after starting time")
        end
      when 'multi_day'
        if self.day > self.end_date
          errors.add(:end_date, "must be after starting date")
        elsif self.day == self.end_date
          if self.end < self.start
            errors.add(:end, "time must be after starting time")
          end
        end
    end
  end

  def self.time_diff(seconds_diff)
    #we are passing this in now
    #seconds_diff = (start_time - end_time).to_i.abs
  
    hours = seconds_diff / 3600
    seconds_diff -= hours * 3600
  
    minutes = seconds_diff / 60
    seconds_diff -= minutes * 60
  
    seconds = seconds_diff
  
    '%01d:%02d' % [hours, minutes]
    #"#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}"
    # or, as hagello suggested in the comments:
    # '%02d:%02d:%02d' % [hours, minutes, seconds]
  end

  def self.update_for_new_columns
    Time.zone = 'Eastern Time (US & Canada)'
    Activity.all.each do |activity|
      activity.start = Time.zone.local(activity.day.year, activity.day.month, activity.day.day, activity.start.hour, activity.start.min, activity.start.sec)
      if activity.name == 'Host Group'
        activity.end = Time.zone.local(activity.day.year, activity.day.month, activity.day.day, activity.start.hour+2, activity.start.min, activity.start.sec)
      else
        activity.end = Time.zone.local(activity.day.year, activity.day.month, activity.day.day, activity.end.hour, activity.end.min, activity.end.sec)
      end
      activity.end_date = activity.day
      activity.activity_type = 'hourly'
      activity.save!
    end
  end

  def modify_dates_bsaed_of_activity_type
    #if user has selected "all_day" or "hourly" for the activity_type
    #then we need to modify the end_date value to reflect the same
    #date for the "day" value (which is the start_date really)
    if %w(all_day hourly).include?(self.activity_type)
      self.end_date = self.day
    end

    if self.activity_type == 'all_day'
      self.start = Time.zone.local(2000,1,1,00,00,00)
      self.end = Time.zone.local(2000,1,1,23,59,59)
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy, :add_worker, :remove_worker]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_worker
    @activity.users << current_user
    alert_camp_admin_of_activity("added")
    respond_to do |format|
      format.js { flash.now[:notice] = "Added you to the activity" }
    end
  end

  def remove_worker
    if params["user"].present?
      @activity.users.delete(User.find(params["user"]))
    else
      @activity.users.delete(current_user)
      alert_camp_admin_of_activity("removed")
    end
    respond_to do |format|
      format.js { flash.now[:notice] = "Removed you from the activity" }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    #send emails if activity is deleted
    def alert_camp_admin_of_activity(method)
      WorkNotifierMailer.let_camp_admin_know(@activity, current_user, method).deliver!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:id, :name, :day, :start, :end_date, :end, :staff_needed, :guest_group_id, :activity_type, :_destroy)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_display_activity.html.erb
<div class="mb-3 border border-info rounded p-3">
  <div class="row">
    <div class="col col-md-9">
      <div class="row mb-1">
        <div class="col-md">
          <div class="text-muted" style="font-size: .9em; margin-bottom: -5px">Activity</div>
          <%=activity.name%><br />

          <div class="text-muted mt-2" style="font-size: .9em; margin-bottom: -5px">When</div>
          <%=activity.day_and_time_span%>

          <%if current_user.camp_admin? || current_user.master_admin?%>
            <div class="text-muted mt-2" style="font-size: .9em; margin-bottom: -5px">Total Staff needed</div>
            <%=activity.staff_needed%>
          <%end%>
        </div>
        <div class="col-md">
          <%if current_user.camp_admin? || current_user.master_admin?%>
            <div class="text-muted" style="font-size: .9em; margin-bottom: -5px">Staff working</div>
            <%activity.users.each do |user|%>
              <div class="mt-2" id="activity_<%=activity.id%>_user_<%=user.id%>">
                <%=user.account.name_with_initial%>
                <%= link_to remove_worker_activity_path(activity.id, user: user.id), method: :post, class: 'btn btn-xs btn-danger text-white ml-2', :remote => true do %>
                  Un-schedule
                <% end %>
              </div>
            <%end%>
          <%else%>
            <div class="text-muted" style="font-size: .9em; margin-bottom: -5px">Total Staff needed</div>
            <%=activity.staff_needed%><br />

            <div class="text-muted mt-2" style="font-size: .9em; margin-bottom: -5px">Staff <%=params['past'] != 'true' ? "working" : "worked"%></div>
            <div id="activity-<%=activity.id%>-workers">
              <%=render "activities/working_names", activity: activity%>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <div class="col-md-3 d-flex flex-column justify-content-center" id="activity-<%=activity.id%>">
      <%unless params['past'] == 'true'%>
        <%=render "activities/working_choices", activity: activity%>
      <%end%>
    </div>
  </div>
</div>

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="field">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>

  <div class="field">
    <%= form.label :staff_needed %>
    <%= form.number_field :staff_needed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/_working_choices.html.erb
<div class="btn-group-vertical">
  <%unless activity.users.count >= activity.staff_needed.to_i || activity.users.map(&:id).include?(current_user.id)%>
    <%= link_to add_worker_activity_path(activity.id), method: :post, class: 'btn btn-sm btn-primary text-white', :remote => true do %>
      Work It
    <% end %>
  <%end%>
  <%if activity.users.map(&:id).include?(current_user.id)%>
    <%if ((Date.today)..(2.weeks.since)).include?(activity.day)%>
      <strong>Within 2 weeks.</strong> Please contat the office if you need to change your work schedule.
    <%elsif activity.day < Date.today%>
      <strong>Activity has already happened</strong>
    <%else%>
      <%= link_to remove_worker_activity_path(activity.id), method: :post, class: 'btn btn-sm btn-danger', :remote => true do %>
        Dont Work It
      <% end %>
    <%end%>
  <%end%>
</div>

app/views/activities/_working_names.html.erb
<%if activity.users.empty?%>
  <%unless params['past'] == 'true'%>
    No one yet, be the first!
  <%end%>
<%else%>
  <%=activity.users.map(&:account).flatten.map(&:name_with_initial).map{|name| name == current_user.account.name_with_initial ? "You" : name}.join(", ")%>
<%end%>

app/views/activities/add_worker.js.erb
$("#info").html("<%= flash[:notice] %>").show(function() {
  setTimeout(function() {
    $("#info").fadeOut('slow');
  }, 4000)
});
$("#activity-<%=@activity.id%>").html("<%= escape_javascript render 'activities/working_choices', activity: @activity %>")
$("#activity-<%=@activity.id%>-workers").html("<%= escape_javascript render 'activities/working_names', activity: @activity %>")

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start</th>
      <th>End</th>
      <th>Staff needed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.name %></td>
        <td><%= activity.start %></td>
        <td><%= activity.end %></td>
        <td><%= activity.staff_needed %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/remove_worker.js.erb
$("#info").html("<%= flash[:notice] %>").show(function() {
  setTimeout(function() {
    $("#info").fadeOut('slow');
  }, 4000)
});
<%if params["user"].present?%>
  $("#activity_<%=@activity.id%>_user_<%=params['user']%>").remove()
<%else%>
if ($("#activity-<%=@activity.id%>").length > 0) {
  $("#activity-<%=@activity.id%>").html("<%= escape_javascript render 'activities/working_choices', activity: @activity %>")
  $("#activity-<%=@activity.id%>-workers").html("<%= escape_javascript render 'activities/working_names', activity: @activity %>")
} else {
  $("#activity_<%=@activity.id%>-listing").remove()
}
<%end%>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Start:</strong>
  <%= @activity.start %>
</p>

<p>
  <strong>End:</strong>
  <%= @activity.end %>
</p>

<p>
  <strong>Staff needed:</strong>
  <%= @activity.staff_needed %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>