config/routes.rb
Rails.application.routes.draw do
  resources :activities do
    member do
      post 'add_worker'
      post 'remove_worker'
    end
  end
  resources :guest_groups, except: [:index]
  resources :camps do
    collection do
      post 'send_invite'
      post 'remove_account_from_camp'
      post 'get_report_data'
    end
    member do
      get 'camp_staff'
      get 'reporting'
    end
  end
  resources :accounts, except: [:show, :index]
  devise_for :users, :controllers => { :invitations => 'users/invitations' }
  patch "users/update"
  get "schedules/index"
  get "schedules/your_work_schedule"
  root "schedules#index"
end

app/views/layouts/_error_display.html.erb
<% if errors.any? %>
  <div class="row">
    <div class="col">
      <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading"><%= pluralize(errors.count, "error") %> stopped this <%=params["controller"].humanize.titleize.singularize%> from being saved:</h4>
        <% errors.full_messages.each do |message| %>
          <%= message %><br />
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_nav_bar.html.erb
<%unless current_user.nil?%>
  <nav class="d-print-none navbar navbar-light bg-light" style='position: sticky; top: 0; z-index: 10'><%#=link_to 'Edit Camp', edit_camp_path(@camp), class: "btn btn-info btn-sm btn-block ml-0 mb-3 text-white" if (current_user.camp_admin? && current_user.camp == @camp) || current_user.master_admin?%>
    <div class="d-md-none">
      <span onclick="openNav()"><i class="fas fa-bars fa-2x"></i></span>
      <!--<a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"><i class="fas fa-bars fa-2x"></i></a>-->
    </div>
    <%if (current_user.camp_admin? && current_user.camp == @camp) || current_user.master_admin?%>
      <%= link_to "#{current_user.camp.name} <i class='fas fa-pencil-alt' style='display: none;'></i>".html_safe, edit_camp_path(current_user.camp_id), class: "navbar-brand btn btn-link"  if (current_user.camp_admin? && current_user.camp == @camp) || current_user.master_admin?%>
    <%else%>
      <div class='navbar-brand'><%=current_user.camp.name%></div>
    <%end%>
    <div class="btn-group text-right">
      <button type="button" class="btn btn-link dropdown-toggle d-flex align-items-center" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user-circle fa-2x mr-1"></i> <%=current_user.account.nil? ? current_user.email : current_user.account.first_name%>
      </button>
      <div class="dropdown-menu dropdown-menu-right" style=" right: 0;left: auto;">
        <%= link_to 'Edit Account', edit_account_path(current_user.account), class: "btn btn-link btn-block text-right" unless current_user.account.nil?%>
        <%= link_to 'My Work Schedule', schedules_your_work_schedule_path, class: "btn btn-link btn-block text-right"%>
        <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-link btn-block text-right" %>
      </div>
    </div>
  </nav>
<%end%>

<div id="mySidenav" class="d-print-none sidenav">
  <div class="row">
    <div class='col'>
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()"><i class="fas fa-times fa-2x"></i></a>
      <%=render 'layouts/sidebar_options'%>
    </div>
  </div>
</div>

app/views/layouts/_sidebar_options.html.erb
<%if current_user.master_admin?%>
  <div class="dropdown mr-auto mb-3">
    <button class="btn btn-secondary text-left btn-block dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Camps
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <%=link_to "View Camps", camps_path, class: "dropdown-item"%>
      <%=link_to "Add New Camp", new_camp_path, class: "nav-link btn btn-link"%>
    </div>
  </div>
<%end%>

<% if !current_user.user? && current_user.camp == @camp%>
  <%#if params['past'] != 'true' && (params[:controller] == 'schedules' && params["action"] == 'index')%>
    <%#= link_to 'Past Groups', root_path(past: true), class: "btn btn-secondary text-white btn-sm btn-block mt-2"%>
  <%#else%>
    <%= link_to 'Guest Groups', root_path, class: "btn btn-secondary text-white btn-sm btn-block mt-2"%>
  <%#end%>
  <%= link_to 'New Guest Group', new_guest_group_path, class: "btn btn-success btn-sm btn-block text-white"%>
  <%= link_to 'Staff Members', camp_staff_camp_path(@camp), class: "btn btn-primary btn-sm btn-block text-white"%>
  <%= link_to 'Reporting', reporting_camp_path(@camp), class: 'btn btn-info btn-sm btn-block'%>
<%else%>
  <%= link_to 'View Upcoming Groups', root_path, class: "btn btn-primary btn-sm btn-block mt-2 text-white"%>
  <%= link_to 'View Work Schedule', schedules_your_work_schedule_path, class: "btn btn-primary btn-sm btn-block mt-2 text-white"%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CampFacilitator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', 'jquery-ui' %>
    <%= javascript_include_tag 'application', 'all' %>
    <!--Bootstrap Integration-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.css" integrity="sha256-CNwnGWPO03a1kOlAsGaH5g8P3dFaqFqqGFV/1nkX5OU=" crossorigin="anonymous" />
    <script src="https://cdn.ckeditor.com/ckeditor5/16.0.0/classic/ckeditor.js"></script>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= yield :head %>
  </head>

  <body>
    <%if current_user.blank?%>
      <div class="row m-3">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    <%else%>
      <div class="row mx-0" id='exmain'>
        <div class="d-print-none col-xl-2 col-lg-3 col-md-4 d-none d-md-block" style="background: rgba(18, 28, 71, 1); height: 100vh; position: sticky; top: 0">
          <div class="row">
            <div class="col text-center pt-2">
              <%=image_tag "camp scheduler logo", style: 'width: 100%'%>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col">
              <%if current_user%>
                <%=render 'layouts/sidebar_options'%>
              <%end%>
            </div>
          </div>
        </div>
        <div class="col px-0">
          <%=render "layouts/nav_bar" unless ["sessions", "registrations", "passwords"].include?(controller_name)%>
          <div class="cal alert alert-info" id="info" role="alert" style="display: <%= notice ? 'block' : 'none'%>"><%= notice %></div>
          <div class="cal alert alert-danger" id="alert" role="alert" style="display: <%= alert ? 'block' : 'none'%>"><%= alert %></div>
          <div class="row m-3">
            <div class="col">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    <%end%>
    <!--Bootstrap Integration-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <%#= javascript_include_tag 'jquery.mask' %>

    <script>
      if($("#info, #alert").length) {
        setTimeout(function(){
          $("#info, #alert").fadeOut('slow');
        }, 4000)
      }
      var jQuery = $
    </script>
    <%= yield :bottom_script %>
  </body>
</html>